import "package:flutter/material.dart";

class MaterialTheme {
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd5bbfc),
      surfaceTint: Color(0xffd5bbfc),
      onPrimary: Color(0xff3a255b),
      primaryContainer: Color(0xff513c73),
      onPrimaryContainer: Color(0xffecdcff),
      secondary: Color(0xffcec2db),
      onSecondary: Color(0xff352d40),
      secondaryContainer: Color(0xff4c4357),
      onSecondaryContainer: Color(0xffeadef7),
      tertiary: Color(0xfff1b7c3),
      onTertiary: Color(0xff4b252e),
      tertiaryContainer: Color(0xff643b44),
      onTertiaryContainer: Color(0xffffd9df),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xFF11071F),
      onSurface: Color(0xffe7e0e8),
      onSurfaceVariant: Color(0xffcbc4cf),
      outline: Color(0xff958e99),
      outlineVariant: Color(0xff4a454e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe7e0e8),
      inversePrimary: Color(0xff6a548d),
      primaryFixed: Color(0xffecdcff),
      onPrimaryFixed: Color(0xff250e45),
      primaryFixedDim: Color(0xffd5bbfc),
      onPrimaryFixedVariant: Color(0xff513c73),
      secondaryFixed: Color(0xffeadef7),
      onSecondaryFixed: Color(0xff1f182a),
      secondaryFixedDim: Color(0xffcec2db),
      onSecondaryFixedVariant: Color(0xff4c4357),
      tertiaryFixed: Color(0xffffd9df),
      onTertiaryFixed: Color(0xff32101a),
      tertiaryFixedDim: Color(0xfff1b7c3),
      onTertiaryFixedVariant: Color(0xff643b44),
      surfaceDim: Color(0xff151218),
      surfaceBright: Color(0xFF1A0B2E),
      surfaceContainerLowest: Color(0xff100d12),
      surfaceContainerLow: Color(0xff1d1a20),
      surfaceContainer: Color(0xff211e24),
      surfaceContainerHigh: Color(0xff2c292f),
      surfaceContainerHighest: Color(0xff37333a),
    );
  }

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF5B3975), // Slightly deeper, more elegant purple
      surfaceTint: Color(0xFF5B3975),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFF1E6FF), // Soft lavender container
      onPrimaryContainer: Color(0xFF21103D),
      secondary: Color(0xFF6B587B),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF5EAFC),
      onSecondaryContainer: Color(0xFF261830),
      tertiary: Color(0xFF8A4D59),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDADE),
      onTertiaryContainer: Color(0xFF370B17),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFCF8FF), // Cleaner, slightly cooler white
      onSurface: Color(0xFF1C1B1F),
      onSurfaceVariant: Color(0xFF49454F),
      outline: Color(0xFF7A757F),
      outlineVariant: Color(0xFFCBC4CF),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF313033),
      inversePrimary: Color(0xFFD5BBFC),
      primaryFixed: Color(0xFFF1E6FF),
      onPrimaryFixed: Color(0xFF21103D),
      primaryFixedDim: Color(0xFFD5BBFC),
      onPrimaryFixedVariant: Color(0xFF5B3975),
      secondaryFixed: Color(0xFFF5EAFC),
      onSecondaryFixed: Color(0xFF261830),
      secondaryFixedDim: Color(0xFFCEC2DB),
      onSecondaryFixedVariant: Color(0xFF6B587B),
      tertiaryFixed: Color(0xFFFFDADE),
      onTertiaryFixed: Color(0xFF370B17),
      tertiaryFixedDim: Color(0xFFF1B7C3),
      onTertiaryFixedVariant: Color(0xFF8A4D59),
      surfaceDim: Color(0xFFDED8E1),
      surfaceBright: Color(0xFFFCF8FF),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF7F2FA),
      surfaceContainer: Color(0xFFF3EDF7),
      surfaceContainerHigh: Color(0xFFEEE8F1),
      surfaceContainerHighest: Color(0xFFE8E2EB),
    );
  }
}

